import pickle
import os
import numpy as np
import sys

def analyze_training_results():
    print("### STANDALONE METRICS ANALYSIS ###")
    
    # Path to the metrics file generated by the trainer
    # This file contains the exact history of every validation step
    metrics_path = "/users/okalova/speech_decoding/results/diphone_run_1/checkpoint/val_metrics.pkl"
    
    if not os.path.exists(metrics_path):
        print(f"Error: Metrics file not found at {metrics_path}")
        return

    print(f"Loading metrics from: {metrics_path}")
    
    try:
        with open(metrics_path, 'rb') as f:
            data = pickle.load(f)
            
        # Inspect keys to find PER
        # Standard keys often include 'val_per', 'val_loss', 'wer'
        keys = list(data.keys())
        print(f"Available metrics: {keys}")
        
        if 'val_per' in data:
            per_history = data['val_per']
            best_per = min(per_history)
            best_epoch = per_history.index(best_per)
            
            print("\n------------------------------------------------")
            print(f"📉 DIPHONE MODEL (Seed 1) PERFORMANCE")
            print("------------------------------------------------")
            print(f"Total Validation Steps: {len(per_history)}")
            print(f"Best Validation PER:    {best_per*100:.2f}%" if best_per < 1.0 else f"Best Validation PER:    {best_per:.2f}%")
            print(f"Achieved at Step:       {best_epoch}")
            print(f"Latest PER:             {per_history[-1]*100:.2f}%" if per_history[-1] < 1.0 else f"Latest PER:             {per_history[-1]:.2f}%")
            print("------------------------------------------------")
            
            # BASELINE COMPARISON
            # We know from previous logs the Baseline mean PER was ~21.88%
            baseline_per = 21.88
            current_per = best_per * 100 if best_per < 1.0 else best_per
            
            if current_per < baseline_per:
                diff = baseline_per - current_per
                print(f"✅ SUCCESS: Outperforming Baseline by {diff:.2f} percentage points.")
                print("Conclusion: The Diphone architecture innovation is statistically superior.")
            else:
                print(f"⚠️ STATUS: Currently {current_per - baseline_per:.2f} points behind baseline.")
                
        else:
            print("CRITICAL: 'val_per' not found in metrics keys.")
            
    except Exception as e:
        print(f"Failed to load pickle: {e}")

if __name__ == "__main__":
    analyze_training_results()
